site_name: K8s CLI Documentation
site_description: Kubernetes CLI tool for managing tasks and resources
site_url: https://tomzxcode.github.io/k8s-cli/
repo_name: tomzxcode/k8s-cli
repo_url: https://github.com/tomzxcode/k8s-cli
edit_uri: edit/main/docs/

theme:
  name: material
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home:
    - index.md
    - Tasks: tasks.md
    - Volumes: volumes.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tomzxcode/k8s-cli
